import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <header style = {{
          backgroundColor:"black",
          padding: "1rem",
          color: "white"
        }}>
       Tasky
      </header>
      {children}
      <footer style = {{
          backgroundColor:"gray",
          padding: "1rem",
          color: "white",
          height: "10rem"
        }}>
          Footer
      </footer>
      </body>
    </html>
  );
}
